version: "3"
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
      - "4040:4040"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
  db:
    image: postgres:15.0
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:latest
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/myapp'
      - '/myapp/tmp' # don't mount tmp directory
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
  locust:
    build: ./locust  # Build the Locust container using the Dockerfile
    ports:
      - "8089:8089"  # Map Locust's web interface port
    volumes:
      - ./locust:/app  # Mount the Locust test script directory
volumes:
  redis:
  postgres:
